# -*- coding: utf-8 -*-
"""Uri1277.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HF8taWuKvEc_8NSzKFZf58krcFYLreOg
"""

n = int(input())


for i in range(n):

  qalunos = int(input());
  nalunos = input().split();
  palunos = input().split();
  c = 0;
  for b in palunos:
    presenca = 0;
    ausencia = 0;
    atestado = 0;
    taxa = 0;
    for k in b:
      if k == 'P':
        presenca = presenca+1
      elif k == 'A':
        ausencia = ausencia+1
      elif k == 'M':
        atestado = atestado+1;
        
    taxa = presenca/(presenca+ausencia)
    if taxa < 0.75:
      print(nalunos[c],end = '');
    c = c+1
   
  print("");

