# -*- coding: utf-8 -*-
"""uri1551.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vqvPnDx6cmTDHBXIxph_-HBLYoxRKg0N
"""

N = int(input())


for l in range(N):

  s = input()
  s = s.lower()
  s2 = ''
  for j in range (len(s)):
    if s[j].isalpha():
      s2 = s2 + s[j];
  x = sorted(s2)

  #Dictionary to map repeated strings
  my_dict = {i:x.count(i) for i in x}

  tam = len(my_dict.keys())

  if tam == 26:
    print('frase completa')
  elif tam > 12:
    print('frase quase completa')
  else:
    print('frase mal elaborada')