# -*- coding: utf-8 -*-
"""Uri2157.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Q-5zl7Ut96crsl0H6dIXW9-djbgzLNC
"""

n = int(input());

for i in range (n):
  lista = input().split();
  lista[0] = int(lista[0]);
  lista[1] = int(lista[1]);
  s = '';
  for j in range(lista[0],lista[1]+1):
    s += str(j);
  s = s + s[::-1]
  print(s);